kafka_istio_enabled: true
kafkaUiHost: kafka.<path:ocivault#mosip_domain#latest | base64decode> 
installName: kafka-ui

kafka-ui:
  envs:
    config:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka.kafka:9092
      KAFKA_CLUSTERS_0_NAME: main_kafka
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper.kafka:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-service.reporting:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_1_ADDRESS: http://es-connect.reporting:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_1_NAME: es-connect
  image:
    pullPolicy: Always



kafka:
  clusterDomain: cluster.local
  logRetentionBytes: _1073741824
  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  numPartitions: 20
  replicaCount: 5
  sidecars: {}
  autoCreateTopicsEnable: true
  # CAUTION: Option to delete topics should be disabled in production. 
  deleteTopicEnable: true

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    storageClass: longhorn

  zookeeper:
    replicaCount: 5
    persistence:
      enabled: true
      size: 2Gi
      storageClass: longhorn

  resources:
    limits: {}
    #   cpu: 250m
    #   memory: 1Gi
    requests: 
      cpu: 200m
      memory: 2000Mi

  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
