apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: all-hosts
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: somesecret 
      mode: SIMPLE