apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
---

