apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-id-account-mapper-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/ddevadat/gitops-poc'
    targetRevision: HEAD
    path: argocd/id-account-mapper
    plugin:
      name: argocd-vault-plugin-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true