apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc 
    namespace: cert-manager
  project: default
  sources:
    - chart: cert-manager
      helm:
        releaseName: cert-manager
        values: |
          installCRDs: true
      repoURL: 'https://charts.jetstack.io'
      targetRevision: 1.15.3

    - chart: cert-manager-webhook-oci
      helm:
        releaseName: cert-manager-webhook-oci
      repoURL: 'https://dn13.gitlab.io/cert-manager-webhook-oci'
      targetRevision: 1.2.1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
