ansibleenv:
  zone_compartment_id: <path:ocivault#zone_compartment_id#latest | base64decode>
  domain: <path:ocivault#openg2p_domain#latest | base64decode>

domain_ssl_secret_name: <path:ocivault#openg2p_domain_ssl_secret_name#latest | base64decode>


gateway: 
  defaults:
    env: 
      ISTIO_META_IDLE_TIMEOUT: 300s
    label:
        istio: ingressgateway    
    service:
      type: LoadBalancer
      ports:
      - port: 15021
        targetPort: 15021
        name: status-port
        protocol: TCP
      - port: 80
        targetPort: 8080
        name: http2
        protocol: TCP
      - port: 443
        targetPort: 8080
        name: https
        protocol: TCP
      - port: 61616
        targetPort: 61616
        name: activemq
        protocol: TCP
      - port: 5432
        targetPort: 5432
        name: postgres
        protocol: TCP
      annotations: 
        oci.oraclecloud.com/load-balancer-type: "nlb"
        oci-network-load-balancer.oraclecloud.com/internal: "false"
        oci-network-load-balancer.oraclecloud.com/is-preserve-source: "false"
        oci.oraclecloud.com/ingress-ip-mode: "Proxy"
        oci.oraclecloud.com/oci-network-security-groups: <path:ocivault#mosip_public_lb_nsg_id#latest | base64decode>
        oci-network-load-balancer.oraclecloud.com/subnet: <path:ocivault#mosip_public_lb_subnet_id#latest | base64decode>
        oci.oraclecloud.com/security-rule-management-mode: "None"  
        external-dns.alpha.kubernetes.io/hostname: testpub.<path:ocivault#openg2p_domain#latest | base64decode>
      externalTrafficPolicy: "Local"
